{"name": "Нельзя создать пользователя c неверным полем email", "status": "passed", "start": 1719570382319, "stop": 1719570382541, "uuid": "924cc19e-0fbf-493f-a3c8-2fc8c3ef7024", "historyId": "bdea1ed30a18d95de63dbef3b59241da", "testCaseId": "bdea1ed30a18d95de63dbef3b59241da", "fullName": "tests.test_create_user.TestCreateUser#test_create_user_with_incorrect_field_email_code_403", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "DESKTOP-USF6L0H"}, {"name": "thread", "value": "15232-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}