{"name": "Нельзя создать пользователя c неверным полем email", "status": "passed", "start": 1719835341251, "stop": 1719835341474, "uuid": "93b9de28-dcc7-447d-aee3-5c373a73a5be", "historyId": "bdea1ed30a18d95de63dbef3b59241da", "testCaseId": "bdea1ed30a18d95de63dbef3b59241da", "fullName": "tests.test_create_user.TestCreateUser#test_create_user_with_incorrect_field_email_code_403", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "DESKTOP-USF6L0H"}, {"name": "thread", "value": "14036-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}